"""
Core laser simulation modules.

    from core.dfb_laser import DFBLaserParams, q, h, c
    from core.sld_injection import SLDParams, InjectionParams, ...
    from core.million_pulse_comparison import simulate_pulses, ...
    from core.gain_switched_interference import GainSwitchParams, ...
"""
