"""
#9 -- Neural Surrogate for Stochastic Gain-Switched Laser Solver

Trains a conditional MLP that maps operating conditions
    (f_rep, S_inj, duty, I_bias_factor) -> distribution statistics
    (mean_P, std_P, r1, timing_jitter, intensity_CV)

using data generated by the numba JIT pulse solver.

Produces figures in images/neural_surrogate/:
  1. training_loss.png       - train/val MSE vs epoch
  2. parity_plots.png        - predicted vs true for each output metric
  3. continuous_sweep.png    - surrogate curve vs simulator spot-checks
"""

import os
import time
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

from core.dfb_laser import DFBLaserParams, q
from core.million_pulse_comparison import simulate_pulses
from gsdfb.analysis import compute_r1
from gsdfb.plotting import setup_plotting, save_fig, img_dir

# ── Output directory ─────────────────────────────────────────────────────────

OUT_DIR = img_dir('neural_surrogate')


# ── Laser setup ──────────────────────────────────────────────────────────────

laser = DFBLaserParams()
I_th = laser.threshold_current()
setup_plotting()

import matplotlib.pyplot as plt
setup_plotting()

# This script runs as a standalone analysis — all code below is the main pipeline.
# It provides `run_condition()` and `SurrogateMLP` for import by other modules.

print("=" * 70)
print("  Neural Surrogate for Stochastic Gain-Switched Laser")
print("=" * 70)
print(f"  Laser: I_th = {I_th*1e3:.2f} mA, tau_p = {laser.tau_p*1e12:.1f} ps")
print()


# ── Data generation ──────────────────────────────────────────────────────────

# Operating condition grid
F_REP_GHZ = [1, 2, 3, 5, 7, 10]           # GHz
S_INJ_VALS = [0, 1e18, 1e19, 5e19, 1e20]  # m^-3
DUTY_VALS = [0.2, 0.3, 0.4]
I_BIAS_FACTORS = [0.8, 0.9, 1.0]          # x I_th

N_PULSES = 20000
N_DISCARD = 200
DT = 1.0e-12
I_PEAK_FACTOR = 5.0


def run_condition(f_rep_ghz, s_inj, duty, i_bias_factor, seed=42):
    """Run simulator for one operating condition, return statistics."""
    f_rep = f_rep_ghz * 1e9
    T_rep = 1.0 / f_rep
    t_on = duty * T_rep
    pts_period = max(int(round(T_rep / DT)), 50)
    dt_actual = T_rep / pts_period
    t_rise = min(20e-12, t_on / 4.0)

    I_off = i_bias_factor * I_th
    I_on = I_PEAK_FACTOR * I_th

    peak_phi, peak_S, samp_S, peak_k = simulate_pulses(
        N_PULSES + N_DISCARD, N_DISCARD, pts_period, dt_actual,
        I_off, I_on, t_on, t_rise,
        laser.V, laser.Gamma, laser.v_g, laser.a, laser.N_tr, laser.epsilon,
        laser.A, laser.B, laser.C, laser.tau_p, laser.beta_sp, laser.alpha_H, q,
        s_inj, seed)

    # Output power
    peak_P = laser.output_power(np.maximum(peak_S, 0))

    # Statistics
    mean_P = np.mean(peak_P)
    std_P = np.std(peak_P)

    # Phase correlation r1
    r1, _ = compute_r1(peak_phi)

    # Timing jitter: std of peak position in time
    sig_t = np.std(peak_k * dt_actual)

    # Intensity CV
    cv = std_P / mean_P if mean_P > 0 else 0.0

    return mean_P, std_P, r1, sig_t, cv


# Generate training data
print("Generating training data...")
print(f"  Grid: {len(F_REP_GHZ)} x {len(S_INJ_VALS)} x {len(DUTY_VALS)} x "
      f"{len(I_BIAS_FACTORS)} = "
      f"{len(F_REP_GHZ)*len(S_INJ_VALS)*len(DUTY_VALS)*len(I_BIAS_FACTORS)} conditions")
print(f"  {N_PULSES} pulses per condition")

# Warmup numba
print("  Compiling JIT solver...", end="", flush=True)
t0 = time.time()
_ = simulate_pulses(
    100, 10, 100, 1e-12,
    0.9 * I_th, 5.0 * I_th, 30e-12, 7e-12,
    laser.V, laser.Gamma, laser.v_g, laser.a, laser.N_tr, laser.epsilon,
    laser.A, laser.B, laser.C, laser.tau_p, laser.beta_sp, laser.alpha_H, q,
    0.0, 0)
print(f" done ({time.time()-t0:.1f}s)")

inputs_list = []
outputs_list = []
total_conditions = len(F_REP_GHZ) * len(S_INJ_VALS) * len(DUTY_VALS) * len(I_BIAS_FACTORS)
count = 0
t_start = time.time()

for f_rep_ghz in F_REP_GHZ:
    for s_inj in S_INJ_VALS:
        for duty in DUTY_VALS:
            for i_bias_factor in I_BIAS_FACTORS:
                seed = hash((f_rep_ghz, s_inj, duty, i_bias_factor)) % (2**31)
                mean_P, std_P, r1, sig_t, cv = run_condition(
                    f_rep_ghz, s_inj, duty, i_bias_factor, seed=seed)

                inputs_list.append([f_rep_ghz, s_inj, duty, i_bias_factor])
                outputs_list.append([mean_P, std_P, r1, sig_t, cv])

                count += 1
                if count % 30 == 0 or count == total_conditions:
                    elapsed = time.time() - t_start
                    rate = count / elapsed
                    eta = (total_conditions - count) / rate if rate > 0 else 0
                    print(f"  [{count}/{total_conditions}] "
                          f"{elapsed:.0f}s elapsed, ETA {eta:.0f}s")

t_gen = time.time() - t_start
print(f"\n  Data generation complete: {t_gen:.1f}s "
      f"({t_gen/total_conditions:.2f}s per condition)")

X = np.array(inputs_list, dtype=np.float64)   # (270, 4)
Y = np.array(outputs_list, dtype=np.float64)  # (270, 5)


# ── Normalization ────────────────────────────────────────────────────────────

# Normalize inputs to [0, 1]
X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_range = X_max - X_min
X_range[X_range == 0] = 1.0  # prevent division by zero
X_norm = (X - X_min) / X_range

# Normalize outputs to [0, 1]
Y_min = Y.min(axis=0)
Y_max = Y.max(axis=0)
Y_range = Y_max - Y_min
Y_range[Y_range == 0] = 1.0
Y_norm = (Y - Y_min) / Y_range

print(f"\n  Output ranges:")
labels = ['mean_P (W)', 'std_P (W)', 'r1', 'sig_t (s)', 'CV']
for i, lbl in enumerate(labels):
    print(f"    {lbl:12s}: [{Y_min[i]:.3e}, {Y_max[i]:.3e}]")


# ── Train/validation split ───────────────────────────────────────────────────

n_total = len(X_norm)
n_val = int(0.2 * n_total)
n_train = n_total - n_val

rng = np.random.default_rng(123)
indices = rng.permutation(n_total)
train_idx = indices[:n_train]
val_idx = indices[n_train:]

X_train = torch.tensor(X_norm[train_idx], dtype=torch.float64)
Y_train = torch.tensor(Y_norm[train_idx], dtype=torch.float64)
X_val = torch.tensor(X_norm[val_idx], dtype=torch.float64)
Y_val = torch.tensor(Y_norm[val_idx], dtype=torch.float64)

print(f"\n  Train: {n_train}, Validation: {n_val}")


# ── MLP model ───────────────────────────────────────────────────────────────

class SurrogateMLP(nn.Module):
    """4 inputs -> 64 -> 64 -> 64 -> 5 outputs."""

    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(4, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 5),
        )
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x):
        return self.net(x)


model = SurrogateMLP().double()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=2000, eta_min=1e-5)
criterion = nn.MSELoss()


# ── Training ─────────────────────────────────────────────────────────────────

N_EPOCHS = 2000

print(f"\n  Training MLP for {N_EPOCHS} epochs...")
t_train_start = time.time()

train_losses = []
val_losses = []

for epoch in range(N_EPOCHS):
    model.train()
    pred = model(X_train)
    loss = criterion(pred, Y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    scheduler.step()

    train_losses.append(loss.item())

    # Validation
    model.eval()
    with torch.no_grad():
        val_pred = model(X_val)
        val_loss = criterion(val_pred, Y_val)
    val_losses.append(val_loss.item())

    if (epoch + 1) % 500 == 0:
        print(f"    Epoch {epoch+1:5d}: train={loss.item():.6f}, "
              f"val={val_loss.item():.6f}")

t_train = time.time() - t_train_start
print(f"  Training complete: {t_train:.1f}s")
print(f"  Final: train MSE = {train_losses[-1]:.6f}, "
      f"val MSE = {val_losses[-1]:.6f}")


# ── Figure 1: Training loss ─────────────────────────────────────────────────

fig1, ax1 = plt.subplots(figsize=(8, 5))
epochs = np.arange(1, N_EPOCHS + 1)
ax1.semilogy(epochs, train_losses, 'b-', lw=1, alpha=0.8, label='Train')
ax1.semilogy(epochs, val_losses, 'r-', lw=1, alpha=0.8, label='Validation')
ax1.set_xlabel('Epoch')
ax1.set_ylabel('MSE Loss (normalized)')
ax1.set_title('Neural Surrogate Training Loss')
ax1.legend()
ax1.grid(True, alpha=0.3)
plt.tight_layout()
save_fig(fig1, os.path.join(OUT_DIR, 'training_loss.png'))


# ── Figure 2: Parity plots ──────────────────────────────────────────────────

model.eval()
with torch.no_grad():
    Y_val_pred_norm = model(X_val).numpy()

# De-normalize predictions and true values
Y_val_true = Y_norm[val_idx] * Y_range + Y_min
Y_val_pred = Y_val_pred_norm * Y_range + Y_min

output_labels = [
    ('Mean Peak Power', 'mW', 1e3),
    ('Std Peak Power', 'mW', 1e3),
    ('Phase Correlation $r_1$', '', 1.0),
    ('Timing Jitter $\\sigma_t$', 'ps', 1e12),
    ('Intensity CV', '', 1.0),
]

fig2, axes2 = plt.subplots(2, 3, figsize=(14, 9))
axes_flat = axes2.flatten()

for i, (name, unit, scale) in enumerate(output_labels):
    ax = axes_flat[i]
    true_scaled = Y_val_true[:, i] * scale
    pred_scaled = Y_val_pred[:, i] * scale

    ax.scatter(true_scaled, pred_scaled, c='steelblue', alpha=0.7, s=30)

    # Perfect agreement line
    vmin = min(true_scaled.min(), pred_scaled.min())
    vmax = max(true_scaled.max(), pred_scaled.max())
    margin = (vmax - vmin) * 0.05
    ax.plot([vmin - margin, vmax + margin], [vmin - margin, vmax + margin],
            'k--', lw=1, alpha=0.7)

    # R^2
    ss_res = np.sum((true_scaled - pred_scaled)**2)
    ss_tot = np.sum((true_scaled - np.mean(true_scaled))**2)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    ax.set_xlabel(f'True ({unit})' if unit else 'True')
    ax.set_ylabel(f'Predicted ({unit})' if unit else 'Predicted')
    ax.set_title(f'{name}\n$R^2$ = {r2:.4f}')
    ax.grid(True, alpha=0.3)

# Hide unused subplot
axes_flat[5].axis('off')

fig2.suptitle('Neural Surrogate: Predicted vs True (Validation Set)', fontsize=13)
plt.tight_layout()
save_fig(fig2, os.path.join(OUT_DIR, 'parity_plots.png'))


# ── Figure 3: Continuous sweep ───────────────────────────────────────────────

# Surrogate: sweep f_rep continuously, fixed S_inj=0, duty=0.3, I_bias=0.9
print("\n  Continuous f_rep sweep with surrogate...")

f_sweep = np.linspace(1, 10, 100)  # GHz
X_sweep_raw = np.column_stack([
    f_sweep,
    np.zeros(100),       # S_inj = 0
    np.full(100, 0.3),   # duty = 0.3
    np.full(100, 0.9),   # I_bias_factor = 0.9
])
X_sweep_norm = (X_sweep_raw - X_min) / X_range
X_sweep_t = torch.tensor(X_sweep_norm, dtype=torch.float64)

model.eval()
with torch.no_grad():
    Y_sweep_norm = model(X_sweep_t).numpy()
Y_sweep = Y_sweep_norm * Y_range + Y_min

# Spot-check at a few frequencies with the simulator
spot_freqs = [1, 2, 4, 6, 8, 10]
print(f"  Running spot-checks at f_rep = {spot_freqs} GHz...")
spot_results = []
for f in spot_freqs:
    seed = hash((f, 0, 0.3, 0.9)) % (2**31)
    mean_P, std_P, r1, sig_t, cv = run_condition(f, 0, 0.3, 0.9, seed=seed)
    spot_results.append([mean_P, std_P, r1, sig_t, cv])
    print(f"    {f} GHz: mean_P={mean_P*1e3:.3f} mW, r1={r1:.4f}, "
          f"jitter={sig_t*1e12:.2f} ps, CV={cv:.4f}")
spot_results = np.array(spot_results)

fig3, axes3 = plt.subplots(2, 3, figsize=(14, 9))
axes_flat3 = axes3.flatten()

for i, (name, unit, scale) in enumerate(output_labels):
    ax = axes_flat3[i]
    ax.plot(f_sweep, Y_sweep[:, i] * scale, 'b-', lw=2, label='Surrogate')
    ax.scatter(spot_freqs, spot_results[:, i] * scale, c='red', s=60,
               zorder=5, marker='o', label='Simulator')
    ax.set_xlabel('Repetition Rate (GHz)')
    ax.set_ylabel(f'{name} ({unit})' if unit else name)
    ax.set_title(name)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

axes_flat3[5].axis('off')

fig3.suptitle('Neural Surrogate vs Simulator: Continuous $f_{rep}$ Sweep\n'
              '$S_{inj}$=0, duty=0.3, $I_{bias}$=0.9$\\times I_{th}$',
              fontsize=12)
plt.tight_layout()
save_fig(fig3, os.path.join(OUT_DIR, 'continuous_sweep.png'))


# ── Summary ──────────────────────────────────────────────────────────────────

# Compute overall accuracy on validation set
rel_errors = np.abs(Y_val_pred - Y_val_true) / (np.abs(Y_val_true) + 1e-30)
mean_rel_err = np.mean(rel_errors, axis=0) * 100

print("\n" + "=" * 70)
print("  Neural Surrogate Summary")
print("=" * 70)
print(f"  Data generation:   {t_gen:.0f}s ({total_conditions} conditions, "
      f"{N_PULSES} pulses each)")
print(f"  Training:          {t_train:.1f}s ({N_EPOCHS} epochs)")
print(f"  Final train MSE:   {train_losses[-1]:.6f}")
print(f"  Final val MSE:     {val_losses[-1]:.6f}")
print(f"\n  Mean relative errors on validation set:")
for i, (name, _, _) in enumerate(output_labels):
    print(f"    {name:30s}: {mean_rel_err[i]:6.2f}%")
print(f"\n  Total runtime:     {time.time()-t_start:.0f}s")
print("=" * 70)
